name: Workflow Test

on:
  workflow_dispatch:
    inputs:
      name:
        required: false
        type: string
      home:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
